version: '3'
services:
  app:
    build: .
    ports: 
      - 8001:8001
    depends_on:
      - db
  db:
    image: 'postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: ngCashDb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    
